all:
  registrationIdInsertV1:
    enable_login:  off
    
  getNotificationV1:
    enable_login:  off

  monitoringNotificationsKeyV1:
    enable_login:  off

  notificationOpenedTrackingV1:
    enable_login:  off