indexSuccess:
  metas:
    title:        My Jeevansathi - Jeevansathi.com
    robots: noindex,nofollow
  stylesheets:    [myjsnew,style_search,search_popup_screens]
  javascripts:    [albumLayer_js@bottom]
jsmsPerformSuccess:
  stylesheets: [-*,jsms/myjs/jsmsMyjs_css,jsms/hamburger/ham_css,jsms/common/disableRightClick_css]
  javascripts: [-*,jsms/myjs/myjs_js,jsms/contact_engine/contactEngine_js,jsms/myjs/touchswipemyjs_js]
  layout: jsmsMobLayout
jspcPerformSuccess:
  metas:
    title:        My Jeevansathi - Jeevansathi.com
    robots: noindex,nofollow
  stylesheets: [jspc/common/cssRangeSlider,jspc/myjs/myjs,jspc/common/NProgress,jspc/common/3DotLoader]
  javascripts: [jspc/myjs/myjs_js,jspc/myjs/myjs_pcrevamp,jspc/myjs/engBarJs_js,jspc/common/nano]
  layout: jspcLayout
