# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

detailedSuccess:
  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [view_page_css,contactEngine_css,edit_layer_css,autoSuggest_jq_css]
  javascripts:    [search_similar_js@bottom, ivrContact_js@bottom, ivrVerifyPhone_js@bottom, profile_tab_js@bottom, removeBookmark_js@bottom , viewSimilar_js@bottom,emailchecks@bottom,contactEngineLayer_js@bottom,autoSuggest_jq_js@bottom]
noprofileSuccess:
  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:        noindex, nofollow

  stylesheets:    [view_page_css]

  javascripts:    [search_similar_js,ivrContact_js,ivrVerifyPhone_js]
  
printSuccess:
  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [view_page_css]

  javascripts:    []

albumSuccess:
  metas:
    title:           Photos & More
    
  stylesheets:    [slider-small,reg_common_css,search_result_css,eoi_style_css,view_page_css,contactEngine_css]
  javascripts:    [search_similar_js,ivrContact_js,ivrVerifyPhone_js,profile_album_js@bottom,photo_slider@bottom,contactEngineLayer_js@bottom]


editSuccess:
  metas:
    title:         My Profile - Jeevansathi.com
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [edit_css,edit_layer_css,autoSuggest_jq_css]

  javascripts:    [search_similar_js,ajax_js,ivrContact_js,registration_js@bottom,edit_page_js,autoSelect_js@bottom,autoSuggest_jq_js@bottom,gadget_as_js@bottom,city_country_common,emailchecks@bottom,textbox_hinter@bottom]

edit_dpp_from_filterSuccess:
  http_metas:
    X-UA-Compatible:    IE=8

  javascripts:    [search_similar_js,registration_js,gadget_as_js,advance_search_js]
dppSuccess:
  metas:
    title:        Desired Partner - Jeevansathi.com
  http_metas:
    X-UA-Compatible:    IE=8
    #description:  symfony project
    #keywords:     symfony, project

  stylesheets:    [edit_css,edit_layer_css]

  javascripts:    [edit_page_js]

editProfileSuccess:
  layout:  layoutEdit
editDppSuccess:
  http_metas:
    X-UA-Compatible:    IE=8


jsmb_viewSuccess:
  metas:
    title:        jeevansathi.com
  stylesheets: [-*,photoRequest]
  javascripts: [ajax_js,mobprofile_js@bottom,tracking_js,mobPhotoUpload]
  layout: mobRegLayout
  
jsmb_noprofileSuccess:
  stylesheets: [-*,mobilejs_css,mobilejs_menu_css,mobilejs_slider_css]
  javascripts: [-*]
  layout: mobRegLayout


myprofilemobSuccess:
  metas:
    title:      My Profile
  stylesheets: [-*,jsms/hamburger/ham_css,jsms/profile/ep/mp_css,jsms/profile/ep/revamp_edit_profile_css,jsms/common/commoncss,jsms/common/mediaquery,jsms/photo/photoup,jsms/common/errorBar,jsms/common/disableRightClick_css]
  javascripts: [-*,jquery_validate_js,jsms/profile/ep/mobedit_validator_js,jsms/utility/sessionStorage_js,jsms/profile/ep/submitDetails_js,jsms/profile/ep/mobedit_js,jsms/profile/ep/mobShow_name_js,jsms/profile/ep/mobeditview_js,jsms/profile/ep/hamburger_js,jsms/utility/hamSearch_js,jsms/utility/vSlider_js,jsms/profile/ep/mobeditsave_js,jsms/photo/mobPhotoUpload_v1@bottom,jsms/photo/mobPhotoUploadCommon_js,jsms/photo/photo_upload_js,jsms/photo/photo_privacy_js,jsms/hamburger/ham_js@bottom,jsms/common/disableRightClick_js]
  layout: jsmsMobLayout
 
#jsms/search/mobSearchDropDown_js added by tanu to prevet error. has to be removed
jsmsViewProfileSuccess:
  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
  stylesheets: [-*,jsms/profile/viewProfile/jsmsViewProfile_css,jsms/search/srpcss,jsms/contact_engine/contactEngine,jsms/common/verificationIcon_css,jsms/common/disableRightClick_css]
  javascripts: [-*,jsms/profile/viewProfile/jsmsViewProfile_js,jsms/contact_engine/contactEngine_js,jsms/search/mobSearchDropDown_js,jsms/photo/photoRequestCommon_js,jsms/utility/sessionStorage_js@bottom, jsms/search/viewSimilarMax@bottom,jsms/common/verificationIcon_js@bottom,jsms/common/disableRightClick_js]
  layout: jsmsMobLayout

#dpp Success For JSPC 
jspcDppSuccess:
  metas:
    title:        Desired Partner - Jeevansathi.com
  http_metas:
    X-UA-Compatible:    IE=edge
  stylesheets:    [jspc/profile/edit/dpp/dppEdit_css,jspc/utility/chosen/chosen_css]

  javascripts:    [jspc/search/hslider@bottom,jspc/utility/chosen/chosen_jquery@bottom,jspc/utility/chosen/docsupport/prism@bottom,jsms/common/history_js,jspc/profile/edit/dpp/jspcDppEdit_js@bottom]
  layout: jspcLayout
  
jspcViewProfileSuccess:
  http_metas:
    X-UA-Compatible:    IE=edge
  stylesheets:    [jspc/profile/view/jspcViewProfile_css,jspc/contactEngine/contactEngine_css,jspc/common/NProgress,jspc/common/3DotLoader]

  javascripts:    [jspc/search/hslider@bottom,jspc/profile/view/jspcViewProfile_js@bottom,jspc/contactEngine/contactEngine,jspc/photo/photoRequest_js@bottom,jspc/common/jquerymCustomScrollbarConcat,jspc/contactEngine/contactEngineButtons,jspc/common/nano,jspc/common/photoAlbum@bottom,jspc/common/common_cal@bottom]
  layout: jspcLayout

jspcEditProfileSuccess:
  metas:
    title:        My Profile - Jeevansathi.com
  http_metas:
    X-UA-Compatible:    IE=edge
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
  stylesheets: [jspc/utility/chosen/chosen_css,jspc/profile/view/jspcViewProfile_css,jspc/profile/edit/dpp/dppEdit_css,jspc/profile/edit/profile/jspcEditProfile_css,jspc/profile/edit/profile/jspcCoverPhoto_css,jspc/profile/edit/profile/jspcEditProfileCompletion_css,jspc/phone/phoneVerification_css]
  javascripts: [jspc/search/hslider@bottom,jspc/utility/chosen/chosen_jquery@bottom,jspc/utility/chosen/docsupport/prism@bottom,jsms/utility/sessionStorage_js@bottom,jspc/profile/edit/profile/jspcEditProfile_js@bottom,jspc/profile/edit/profile/jspcCoverPhoto_js@bottom,jspc/profile/edit/profile/jspcEditProfileCompletion_js@bottom,jspc/profile/edit/profile/jspcPhoneVerifyBinding_js@bottom,jspc/common/phoneVeriLayers_js@bottom,jspc/common/nano@bottom,jspc/common/photoAlbum@bottom]
  layout: jspcLayout
  
jspcNoProfileSuccess:
  http_metas:
    X-UA-Compatible:    IE=edge

  stylesheets:    [jspc/profile/view/jspcNoProfile_css,jspc/search/searchBand,jspc/profile/view/jspcViewProfile_css]

  javascripts:    [jspc/search/searchDropdowns@bottom,jspc/search/hslider@bottom,jspc/search/searchBand@bottom,jspc/profile/view/jspcNoProfile_js@bottom]
  layout: jspcLayout
  
mobHoroscopeSuccess:
  stylesheets:    [-*,jsms/profile/horoscope/horoscope_css]

  javascripts:    [-*,jsms/profile/horoscope/horoscope_js]
  layout: jsmsMobLayout
